services:
  ic-replica:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel3-ic-replica
    ports:
      - "8000:8000"  # IC replica API
      - "8080:8080"  # Frontend canister
    volumes:
      - .:/home/ic-user/app
      - dfx-cache:/home/ic-user/.cache/dfx
      - identity:/home/ic-user/.config/dfx/identity
    command: dfx-start
    restart: unless-stopped

  mint-nfts:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ic-replica
    volumes:
      - .:/home/ic-user/app
      - dfx-cache:/home/ic-user/.cache/dfx
      - identity:/home/ic-user/.config/dfx/identity
    command: mint
    # This service will exit after minting is complete

  # Shell for interactive work with dfx tools
  dfx-shell:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/ic-user/app
      - dfx-cache:/home/ic-user/.cache/dfx
      - identity:/home/ic-user/.config/dfx/identity
    command: bash
    stdin_open: true
    tty: true

volumes:
  dfx-cache:
  identity: