services:
  ic-replica:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel3-ic-replica
    ports:
      - "8000:8000"  # IC replica API
      - "8080:8080"  # Frontend canister
    volumes:
      - .:/home/ic-user/project
      # Exclude .dfx directory from the main mount
      - /home/ic-user/project/.dfx
      # Use separate volumes for important directories
      - dfx-data:/home/ic-user/project/.dfx
      - dfx-cache:/home/ic-user/.cache/dfx
      - identity:/home/ic-user/.config/dfx/identity
    entrypoint: []
    command: bash -c "/home/ic-user/project/start-ic.sh"
    restart: always
    user: root
    environment:
      - DFX_TELEMETRY_DISABLED=1
      - RUST_BACKTRACE=1
volumes:
  dfx-data:
  dfx-cache:
  identity: